### PR TITLE
Add code style checks

### PR DESCRIPTION
**Pull request by timonegk**
## Proposed changes
- Add black and ruff for Python
- Add clang-format for C++
- Add pre-commit configuration and workflow that checks both

### CODE REVIEW

**Comment by jaagut** [comment]
Please add some documentation (probably in the meta and our installation guides) how to set it up locally.

**Comment by jaagut** [comment]
This functionally, this should be ready. However, we already have a merge conflict and presumably many more will occur, with #334

**Comment by Flova** [comment]
As the formatting of all these files is automated (i think) we should just accept all incoming changes and rerun the formatting.

**Comment by texhnolyze** [comment]
I've taken this over cleaned up the history to only have two commits for `pre-commit` and ci setup, then got the latest changes from `master` and then autoformatted everything again.

**Review by jaagut — APPROVED** [review]

**Pull request merged**
