### PR TITLE
Fix handling of the role position and init animation in behavior

### PR DESCRIPTION
**Pull request by timonegk**
We tried to play the init animation which was added in simulation and breaks the real robot.
Also, the role position was not handled correctly.

### CODE REVIEW

**Comment by Flova** [comment]
Why do you remove the randomized defender position?

**Comment by jaagut** [comment]
@timonegk is this still in progress or ready for review?

**Comment by Flova** [comment]
I also agree with that. The init is needed in the virtual season, but not in real life.

The roles seem to be fine now, but is could be the case that they are loaded from the behavior config instead of the parameter blackboard.

**Comment by Flova** [comment]
I think this is not needed anymore

**Pull request closed without merging**
